name: Deploying to Vercel and Netlify
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      # Install Node.js 16
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Install dependencies
      - name: Install Dependencies
        run: yarn install
        continue-on-error: false

      # Build the app
      - name: Build
        if: success() || failure() # Run even if tests fail
        run: yarn run build
        continue-on-error: false

      # Deploy to Vercel
      - name: Deploy to Vercel
        if: success() && github.ref == 'refs/heads/main' # Only deploy on successful push to main branch
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: jvCrSsQzBxvOptQnDziZxKL1
          vercel-project-id: prj_R5mBcWd8plLoPoCNiP8Wl0KZxLO6
        continue-on-error: false
        
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.TOKEN_GIT }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      # Merge to main branch
      - name: Merge to Main
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' # Only merge on successful push to main branch
        uses: 'stefanzweifel/git-auto-commit-action@v4'
        with:
          commit_message: "Merge to main branch"
          commit_options: '--no-verify --signoff'
          branch: 'main'
          commit_user_name: ${{ github.name }}
          commit_user_email: ${{ github.email }}@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN_GIT}}
        continue-on-error: false

      # Merge to main branch
      - name: Merge to Main
        if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' # Only merge on successful push to main branch
        run: git merge origin/main --no-edit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false
        
        
 
